config/routes.rb
Rails.application.routes.draw do

  root 'index#index'
  get 'upload', to: 'files#index'
  post 'upload', to: 'files#upload'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/files_controller.rb
class FilesController < ApplicationController

    def index
    end

    def upload
        upload = params[:babyfile]
        name =  upload.original_filename
        directory = "public/data"
        # create the file path
        path = File.join(directory, name)
        # write the file
        File.open(path, "wb") { |f| f.write(upload.read) }
        render :text => "File has been uploaded successfully"
        
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/files_helper.rb
module FilesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/files/index.html.erb
<form method="post" enctype="multipart/form-data" action="<%= upload_path %>">

    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    
    <input type="file" name="babyfile" />
    <input type="submit" name="Upload" />
</form>

app/views/index/index.html.erb
<script src="//embed.flowplayer.org/5.5.2/embed.min.js">
    <div class="flowplayer" style="width: 624px; height: 400px;">
          <video>
             <source type="video/mp4" src="/data/mp4.mp4">
          </video>
    </div>
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Babies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div id="wrapper">
    <h1>Wyaeh.io</h1>
    <%= yield %>

</div>
</body>
</html>